# Generated by Django 5.0.1 on 2024-01-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('datenaissance', models.DateField()),
                ('CNE', models.IntegerField(max_length=16)),
                ('section', models.CharField(max_length=25)),
            ],
        ),
    ]
